### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by souzatharsis** [evandempsey/podcast-llm#8]
Just a congrats message!

Great idea to generate podcast by topic! Your implementation is sound!

Coincidentally, `podcastfy` released a similar feature last week! Generate podcast by topic based on real-time web information:

```python
generate_podcast(topic="Latest news on OpenAI")
```

It leverages newly released Gemini grounded search, which behind the scenes is using google search engine to enable web information retrieval in real-time.

I wonder how are our two implementations compare :)

Keep up the good work!

Cheers,
Tharsis!

**Comment by souzatharsis** [comment]
All sound great developments!

I am mainly focused on trying to generate long-form podcasts, which turns out to be surprisingly challenging (LLMs are trained to give short answers and combining multiple calls together is not straight-forward).

I am curious what specifically did you implement pertaining to "editing phase to introduce speech disfluences to the initial dialog." Could you please point me to a specific part in your code; would love to learn from your implementation.

**Comment by evandempsey** [comment]
Sure. Look at `write_final_script` here [https://github.com/evandempsey/podcast-llm/blob/main/podcast_llm/writer.py](https://github.com/evandempsey/podcast-llm/blob/main/podcast_llm/writer.py)

And here's the prompt on then hub. [https://smith.langchain.com/hub/evandempsey/podcast_rewriter](https://smith.langchain.com/hub/evandempsey/podcast_rewriter)

There are definitely gains to be made by enhancing some of these prompts.

**Comment by souzatharsis** [comment]
I see. You manage to get longer conversations by not only holding Q&A rounds but organizing them around section/subsections to structure the conversation. Plus when you pass the query to the LLM you pass a context of what was discussed. 

That's in the direction of what I am implementing as well as what I am calling "Content Chunking with Contextual Linking" approach to overcome the traditional max output size length limitation in llms.

You should consider exploring agents. That would provide a very elegant way to model your interviewer/interviewee approach which is already very nicely componentized. So the refactor would be straight forward.

**Comment by evandempsey** [comment]
Yes, I initially thought I would use an agent-based approach, but abandoned it because I haven't found an agent approach that feels like it's worth the cost of abstraction. Langgraph certainly isn't it.

I will do further investigation.

**Comment by souzatharsis** [comment]
Microsoft released this today: https://github.com/microsoft/tinytroupe
Sounded simple and effective for our use case?

<http://linkedin.com/in/tharsissouza>

**Comment by souzatharsis** [comment]
Yes, exactly!

We've had this idea for a 'long' time now, where we would have a Character
object giving custom behavior to each speaker.
That's a nice customization direction. However, first I need to sort out my
long-form podcast generation issue... :)

Best Regards,

--
Thársis
souzatharsis.com <http://www.souzatharsis.com/>
<http://linkedin.com/in/tharsissouza>
